# -*- coding: utf-8 -*-

{
    'name': 'Discuss',
    'version': '1.3',
    'category': 'Productivity/Discuss',
    'sequence': 145,
    'summary': 'Chat, mail gateway and private channels',
    'description': "",
    'website': 'https://www.odoo.com/page/discuss',
    'depends': ['base', 'base_setup', 'bus', 'web_tour'],
    'data': [
        'views/assets.xml',
        'wizard/invite_view.xml',
        'wizard/mail_blacklist_remove_view.xml',
        'wizard/mail_compose_message_view.xml',
        'wizard/mail_resend_cancel_views.xml',
        'wizard/mail_resend_message_views.xml',
        'wizard/mail_template_preview_views.xml',
        'views/mail_message_subtype_views.xml',
        'views/mail_tracking_views.xml',
        'views/mail_notification_views.xml',
        'views/mail_message_views.xml',
        'views/mail_mail_views.xml',
        'views/mail_followers_views.xml',
        'views/mail_moderation_views.xml',
        'views/mail_channel_partner_views.xml',
        'views/mail_channel_views.xml',
        'views/mail_shortcode_views.xml',
        'views/mail_activity_views.xml',
        'views/res_config_settings_views.xml',
        'data/ir_config_parameter_data.xml',
        'data/res_partner_data.xml',
        'data/mail_message_subtype_data.xml',
        'data/mail_templates.xml',
        'data/mail_channel_data.xml',
        'data/mail_activity_data.xml',
        'data/ir_cron_data.xml',
        'security/mail_security.xml',
        'security/ir.model.access.csv',
        'views/mail_alias_views.xml',
        'views/res_users_views.xml',
        'views/mail_template_views.xml',
        'views/ir_actions_views.xml',
        'views/ir_model_views.xml',
        'views/res_partner_views.xml',
        'views/mail_blacklist_views.xml',
        'views/mail_menus.xml',
    ],
    'demo': [
        'data/mail_channel_demo.xml',
    ],
    'installable': True,
    'application': True,
    'qweb': [
        'static/src/bugfix/bugfix.xml',
        'static/src/components/activity/activity.xml',
        'static/src/components/activity-box/activity-box.xml',
        'static/src/components/activity-mark-done-popover/activity-mark-done-popover.xml',
        'static/src/components/attachment/attachment.xml',
        'static/src/components/attachment-box/attachment-box.xml',
        'static/src/components/attachment-delete-confirm-dialog/attachment-delete-confirm-dialog.xml',
        'static/src/components/attachment-list/attachment-list.xml',
        'static/src/components/attachment-viewer/attachment-viewer.xml',
        'static/src/components/autocomplete-input/autocomplete-input.xml',
        'static/src/components/chat-window/chat-window.xml',
        'static/src/components/chat-window-header/chat-window-header.xml',
        'static/src/components/chat-window-hidden-menu/chat-window-hidden-menu.xml',
        'static/src/components/chat-window-manager/chat-window-manager.xml',
        'static/src/components/chatter/chatter.xml',
        'static/src/components/chatter-container/chatter-container.xml',
        'static/src/components/chatter-topbar/chatter-topbar.xml',
        'static/src/components/composer/composer.xml',
        'static/src/components/composer-suggested-recipient/composer-suggested-recipient.xml',
        'static/src/components/composer-suggested-recipient-list/composer-suggested-recipient-list.xml',
        'static/src/components/composer-suggestion/composer-suggestion.xml',
        'static/src/components/composer-suggestion-list/composer-suggestion-list.xml',
        'static/src/components/composer-text-input/composer-text-input.xml',
        'static/src/components/dialog/dialog.xml',
        'static/src/components/dialog-manager/dialog-manager.xml',
        'static/src/components/discuss/discuss.xml',
        'static/src/components/discuss-mobile-mailbox-selection/discuss-mobile-mailbox-selection.xml',
        'static/src/components/discuss-sidebar/discuss-sidebar.xml',
        'static/src/components/discuss-sidebar-item/discuss-sidebar-item.xml',
        'static/src/components/drop-zone/drop-zone.xml',
        'static/src/components/editable-text/editable-text.xml',
        'static/src/components/emojis-popover/emojis-popover.xml',
        'static/src/components/file-uploader/file-uploader.xml',
        'static/src/components/follow-button/follow-button.xml',
        'static/src/components/follower/follower.xml',
        'static/src/components/follower-list-menu/follower-list-menu.xml',
        'static/src/components/follower-subtype/follower-subtype.xml',
        'static/src/components/follower-subtype-list/follower-subtype-list.xml',
        'static/src/components/mail-template/mail-template.xml',
        'static/src/components/message/message.xml',
        'static/src/components/message-author-prefix/message-author-prefix.xml',
        'static/src/components/message-list/message-list.xml',
        'static/src/components/message-seen-indicator/message-seen-indicator.xml',
        'static/src/components/messaging-menu/messaging-menu.xml',
        'static/src/components/mobile-messaging-navbar/mobile-messaging-navbar.xml',
        'static/src/components/moderation-ban-dialog/moderation-ban-dialog.xml',
        'static/src/components/moderation-discard-dialog/moderation-discard-dialog.xml',
        'static/src/components/moderation-reject-dialog/moderation-reject-dialog.xml',
        'static/src/components/notification-alert/notification-alert.xml',
        'static/src/components/notification-group/notification-group.xml',
        'static/src/components/notification-list/notification-list.xml',
        'static/src/components/notification-popover/notification-popover.xml',
        'static/src/components/notification-request/notification-request.xml',
        'static/src/components/partner-im-status-icon/partner-im-status-icon.xml',
        'static/src/components/thread-icon/thread-icon.xml',
        'static/src/components/thread-needaction-preview/thread-needaction-preview.xml',
        'static/src/components/thread-preview/thread-preview.xml',
        'static/src/components/thread-textual-typing-status/thread-textual-typing-status.xml',
        'static/src/components/thread-typing-icon/thread-typing-icon.xml',
        'static/src/components/thread-view/thread-view.xml',
        'static/src/view-field-mixins/emojis-common/emojis-common.xml',
        'static/src/view-fields/activity/activity.xml',
        'static/src/view-fields/basic-activity/basic-activity.xml',
        'static/src/view-fields/kanban-activity/kanban-activity.xml',
        'static/src/view-fields/list-activity/list-activity.xml',
        'static/src/view-fields/many2many-tags-email/many2many-tags-email.xml',
        'static/src/view-fields/many2one-avatar-user/many2one-avatar-user.xml',
        'static/src/views/activity/renderer/renderer.xml',
        'static/src/widget-addons/debug-manager/debug-manager.xml',
        'static/src/widgets/activity-menu/activity-menu.xml',
        'static/src/widgets/common.xml',
        'static/src/widgets/discuss/discuss.xml',
        'static/src/widgets/discuss-invite-partner-dialog/discuss-invite-partner-dialog.xml',
        'static/src/widgets/document-viewer/document-viewer.xml',
        'static/src/widgets/messaging-menu/messaging-menu.xml',
    ],
}
