from . import barcode_nomenclature
from . import barcode_rule
from . import ir_http
from . import mail_template
from . import pos_category
from . import pos_config
from . import pos_load_mixin
from . import pos_order_line
from . import pos_order
from . import pos_payment_method
from . import pos_preset
from . import pos_session
from . import pos_snooze
from . import product_product
from . import product_tag
from . import res_config_settings
from . import res_country
from . import res_partner
