{
    "name": "POS Self",
    "summary": "Addon for the POS App that allows customers to view the menu on their smartphone.",
    "category": "Hidden",
    "depends": ["point_of_sale", "http_routing", "link_tracker", "barcodes", "barcodes_gs1_nomenclature"],
    "data": [
        "views/pos_category_views.xml",
        "views/pos_config_view.xml",
        "views/product_views.xml",
        "views/pos_preset_view.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        'point_of_sale._assets_pos': [
            'pos_self/static/src/overrides/**/*',
        ],
        "pos_self.assets": [
            "pos_self/static/src/app/primary_variable.scss",
            "pos_self/static/src/app/bootstrap_overridden.scss",
            ("include", "point_of_sale.base_app"),
            'web/static/src/core/currency.js',
            'barcodes/static/src/barcode_service.js',
            'point_of_sale/static/src/utils.js',
            'point_of_sale/static/src/app/utils/convert_python_template.js',
            'point_of_sale/static/src/proxy_trap.js',
            'point_of_sale/static/src/lazy_getter.js',
            'point_of_sale/static/src/app/utils/init_lna.js',
            'web/static/lib/bootstrap/js/dist/util/index.js',
            'web/static/lib/bootstrap/js/dist/dom/data.js',
            'web/static/lib/bootstrap/js/dist/dom/event-handler.js',
            'web/static/lib/bootstrap/js/dist/dom/manipulator.js',
            'web/static/lib/bootstrap/js/dist/dom/selector-engine.js',
            'web/static/lib/bootstrap/js/dist/util/config.js',
            'web/static/lib/bootstrap/js/dist/util/swipe.js',
            'web/static/lib/bootstrap/js/dist/base-component.js',
            "web/static/lib/bootstrap/js/dist/carousel.js",
            'web/static/lib/bootstrap/js/dist/scrollspy.js',
            'html_editor/static/src/scss/base_style.scss',
            'html_editor/static/src/scss/html_editor.common.scss',
            "point_of_sale/static/src/app/utils/make_awaitable_dialog.js",
            "point_of_sale/static/src/app/components/numpad/*",
            "point_of_sale/static/src/app/components/loader/*",
            "point_of_sale/static/src/app/components/loader/critical_pos_error/*",
            "point_of_sale/static/src/app/components/product_card/*",
            "point_of_sale/static/src/app/components/order_display/*",
            "point_of_sale/static/src/app/components/orderline/*",
            "point_of_sale/static/src/app/components/centered_icon/*",
            "point_of_sale/static/src/app/components/epos_templates.xml",
            "point_of_sale/static/src/css/pos_receipts.css",
            "point_of_sale/static/src/app/utils/printer/*",
            'point_of_sale/static/src/app/utils/html-to-image.js',
            'point_of_sale/static/src/app/utils/use_timed_press.js',
            'point_of_sale/static/src/app/services/pos_ticket_printer_service.js',
            'barcodes/static/src/js/barcode_parser.js',
            'barcodes_gs1_nomenclature/static/src/js/barcode_parser.js',
            'point_of_sale/static/src/app/services/barcode_reader_service.js',
            'point_of_sale/static/src/app/hooks/barcode_reader_hook.js',
            "pos_self/static/src/app/**/*",
            "web/static/src/core/utils/render.js",
            "account/static/src/helpers/*.js",
            'web/static/src/model/relational_model/operation.js',
            "web/static/src/views/fields/parsers.js",

            # Related models from point_of_sale
            "point_of_sale/static/src/app/models/data_service_options.js",
            "point_of_sale/static/src/app/models/utils/indexed_db.js",
            "point_of_sale/static/src/app/models/related_models/**/*",
            "point_of_sale/static/src/app/services/data_service.js",
            "point_of_sale/static/src/app/models/**/*",
            "point_of_sale/static/src/app/utils/numbers.js",
            "point_of_sale/static/src/app/utils/pretty_console_log.js",
            "point_of_sale/static/src/app/utils/devices_identifier_sequence.js",
            "point_of_sale/static/src/app/hooks/hooks.js",
            "point_of_sale/static/src/app/utils/debug-formatter.js",

            ('include', 'point_of_sale.payment_terminals'),
        ],
    },
    "author": "Odoo S.A.",
    "license": "LGPL-3",
}
