# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Web Icons',
    'category': 'Hidden',
    'summary': 'Centralises icon fonts and provides Material Symbols font subsetting tooling.',
    'description': 'See README',
    'depends': ['web'],
    'auto_install': True,
    'assets': {
        'web.material_symbols_outlined': [
            # @font-face CSS generated by `odoo-bin generate_icons`.
            # Points to static/src/fonts/ms_outlined.woff2 (variable font subset).
            '/web_icons/static/src/materialsymbols/material_symbols_outlined.css',
        ],
        'web.material_symbols_sharp': [
            # @font-face CSS for the Sharp variant (user-selectable in website editor).
            '/web_icons/static/src/materialsymbols/material_symbols_sharp.css',
        ],
        'web.odoo_ui_icons': [
            '/web_icons/static/lib/fonts/odoo_ui_icons.woff2',
            '/web_icons/static/lib/fonts/odoo_ui_icons.woff',
            '/web_icons/static/lib/odoo_ui_icons.css',
        ],
        'web.icons_fonts': [
            'web_icons/static/src/icons.scss',
            # Generated by `odoo-bin generate_icons`: per-icon ::before rules.
            'web_icons/static/src/icons_pua.scss',
        ],
        'web.assets_backend': [],
        'web_icons.assets': [
            'web_icons/static/src/services/icon_service.js',
            'web_icons/static/src/material_symbols_icons.js',
        ],
    },
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
}
